name: Build

on:
  push:
  pull_request:

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    env:
      MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up JDK 1.8
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 1.8
      - name: Build
        run: >
          ./mvnw $MAVEN_CLI_OPTS
          dependency:go-offline
          clean verify
